#服务启动端口号
server:
  port: 9105 #定时任务系统应用端口号统一从9101开始累加
  connection-timeout: PT30S #修改请用 System.out.println(Duration.ofSeconds(30))  PT30S  PT1M
  tomcat:
    uri-encoding: UTF-8 #编码格式
    min-spare-threads: 10 #线程最小空闲线程数
    accept-count: 20 #最大线程排队数 默认值为100
    max-threads: 100 #最大同时处理的线程数 默认值为200
    max-connections: 100 #最大连接数
    max-http-post-size: 0  #最大post数据的大小 0表示不限制

#mybatis: 打印完整的sql日志 调试时可开启使用
#    configuration:
#      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#简单日志打印
logging:
  level:
    com.busi.dao:  #dao的路径 和 打印级别

spring:
  application:
    name: quartz_activity #当前项目的对外调用访问的名称
  activemq:
    broker-url: tcp://192.168.1.160:61616?jms.useAsyncSend=true #异步请求
    in-memory: true
    pool:
      enabled: false #false 关闭连接池
      max-connections: 20 #连接池的最大连接数
      idle-timeout: PT30S
#      expiry-timeout: 0 #默认0 从不失效
  datasource:
      url: jdbc:mysql://192.168.1.172:3306/ehome_activity?characterEncoding=utf8&useSSL=false
      username: root
      password: LiChengWang_20180531
      driver-class-name: com.mysql.jdbc.Driver
      platform: mysql
      # 使用druid数据源
      type: com.alibaba.druid.pool.DruidDataSource
      initialSize: 10 # 初始化大小
      minIdle: 3 # 最小空闲连接
      maxActive: 10 # 最大连接
#      maxWait: 60000 # 配置获取连接等待超时的时间
      timeBetweenEvictionRunsMillis: 60000 # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 30000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: stat,wall,slf4j
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      # 合并多个DruidDataSource的监控数据
      #useGlobalDataSourceStat: true

  redis:
    database: 0  #数据库 默认0号库 0库用于存储用户相关信息 1:ips  2:eblog
    host: 192.168.1.162 #单机时需要指定
    password: LiChengWang_redis_20180604
    port: 6379 #单机时需要指定
    timeout: PT10S # 连接超时时间（毫秒）默认是2000  改成10秒 修改请用 System.out.println(Duration.ofSeconds(10))
    jedis:
      pool:
        max-idle: 10 # 连接池中的最大空闲连接
        min-idle: 5 # 连接池中的最小空闲连接
        max-active: 10 #连接池最大连接数
        max-wait: PT24H # 连接池最大阻塞等待时间 改成1天 修改请用 System.out.println(Duration.ofDays(1))
#    sentinel: #哨兵配置
#      master: mymaster #哨兵监听的Redis server的名称
#      nodes: 192.168.1.160:26379 #哨兵多台时，分隔  如192.168.1.160:26379,192.168.1.163:26379

pagehelper: #分页配置
    helperDialect: mysql #数据库类型 oracle,mysql,mariadb,sqlite,hsqldb,postgresql,sqlserver
    reasonable: false  #3.3.0版本可用 - 分页参数合理化，默认false， 启用合理化时，如果pageNum<1会查询第一页，如果pageNum>pages会查询最后一页 禁用合理化时，如果pageNum<1或pageNum>pages会返回空数据
    supportMethodsArguments: true # 默认值false，分页插件会从查询方法的参数值中，自动根据上面 params 配置的字段中取值，查找到合适的值时就会自动分页。
    params: count=countSql

eureka:
  instance:
    hostname: localhost #主机名 目前只能写localhost 否则报错
    prefer-ip-address: true #显示IP
    instance-id: ${spring.application.name}:${spring.application.instance-id:${server.port}}
  client:
    serviceUrl:
      defaultZone: http://192.168.1.160:8761/eureka/

hystrix: #设置超时 三个时间最好保持一致
  threadpool:
    default:
      coreSize: 10
      maximumSize: 10 #最大线程数
      allowMaximumSizeToDivergeFromCoreSize: true #是否让maximumSize生效，false的话则只有coreSize会生效
      maxQueueSize: -1 #线程池的队列大小，-1代表使用SynchronousQueue队列
  command:
    default:
      execution:
        timeout:
          enabled: true #启用超时时间
        isolation:
          thread:
            timeoutInMilliseconds: 60000 #60秒

ribbon: #设置超时 三个时间最好保持一致
  ReadTimeout: 5000 #5秒
  ConnectTimeout: 5000 #5秒
  MaxAutoRetries: 1 # 同一实例最大重试次数，不包括首次调用
  MaxAutoRetriesNextServer: 1 # 重试其他实例的最大重试次数，不包括首次所选的server
  OkToRetryOnAllOperations: true #对所有请求操作都进行重试

